name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt-get install gcc g++ make
    - name: nodejs
      run: sudo apt install nodejs
    - name: express
      run: npm install express
    - name: surge
      run: npm install --global surge
    - name: pip
      run: pip install html5validator
    - name: validator
      run: html5validator --root _build/
    - name: deployer
      run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
